name: Todoey

on:
  workflow_dispatch:

jobs:
  cinco:
    name: Analyze PR
    runs-on: ubuntu-latest
    steps:
      - name: check it out
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Scraper
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_USER: ${{ github.actor }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          python todoey.py
